# 基本配置

# 是否开启多会话模式
multiSession: true
# 是否开启姓名手机号打码
maskAcc: true
# TUI 最大显示高度
tUIMaxHeight: 25
# 会话存档路径
sessionPath: "session/"
# 日志文件路径
logPath: "logs/"

# --------------------

# 任务执行器配置
# 视频
video:
  # 使能
  enable: true  
  # 完成等待时间
  wait: 15
  # 倍速
  speed: 1.0
  # 视频播放汇报率 (没事别改)
  report_rate: 58
  

# 试题
exam:
  # 使能
  enable: true
  # 完成等待时间
  wait: 15
  # TODO: 是否匹配失败自动保存
  # fail_save: true

# 文档
document:
  # 使能
  enable: true
  # 完成等待时间
  wait: 15

# --------------------

# 搜索器选择 (可同时使用多个搜索器, 以 yaml 语法中 list 格式添加, `type`字段决定搜索器类型)
# 可用的搜索器有: restApiSearcher jsonFileSearcher sqliteSearcher enncySearcher
searchers:
  # 本地 JSON 数据库搜索器 (key为题, value为答案)
  - type: jsonFileSearcher
    file_path: "questions.json"  # 数据库文件路径

  # REST API 在线搜题
  # - type: restApiSearcher
  #   url: "http://127.0.0.1:88/v1/cx"  # API url
  #   method: "POST"  # 请求方式
  #   req_field: "question"  # 请求参数
  #   headers:  # 自定义请求头(可选) 使用 yaml 的 k-v 语法填写
  #     # eg: Authorization: 'xxx'
  #   ext_params: # 自定义扩展请求参数(可选) 使用 yaml 的 k-v 语法填写
  #     # eg: Token: 'xxx'
  #   rsp_field: "$.data"  # 返回参数 使用 JSONPath 语法进行查询
  
  # 本地 sqlite 数据库搜索器
  # - type: sqliteSearcher
  #   file_path: "questions.db"  # 数据库文件路径
  #   table: "question"  # 表名
  #   req_field: "question"  # 请求字段
  #   rsp_field: "answer"  # 返回字段

  # Enncy 题库搜索器，使用前请注册 https://tk.enncy.cn/
  # - type: enncySearcher
  #   token: "xxx"  # Enncy 题库 Token

  # 网课小工具(Go题)题库搜索器，使用前请获取Token https://cx.icodef.com/1-UserGuide/1-6-gettoken.html#%E8%8E%B7%E5%8F%96token
  # - type: cxSearcher
  #   token: "xxx"  # 网课小工具(Go题)题库 Token